/**
 * Manual UI smoke harness for the account area.
 *
 * Not a test: it boots the real server against a throwaway database with one
 * signed-in customer, seeds the order shapes the account page has to render
 * (delivery, pickup, promo, cancelled, a pre-promotion row, and a customer with
 * no orders at all), and prints the cookie to paste into a browser alongside the
 * URL to open. Asserting on rendered React would need a DOM test runner, which
 * this project does not have; this covers "the endpoints the page calls answer
 * correctly with a real session" and leaves the visual pass to a human.
 *
 * Run: npm run smoke:account-ui -w server
 */
import { spawn, type ChildProcess } from "child_process";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const SERVER_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const THROWAWAY = path.join(SERVER_ROOT, "smoke_ui.db");
const CHILD_ENV_FILE = path.join(SERVER_ROOT, ".env.smoke-ui");
const tsxCli = path.join(SERVER_ROOT, "..", "node_modules", "tsx", "dist", "cli.mjs");
const PORT = 5196;
const BASE = `http://127.0.0.1:${PORT}`;

function dbFiles() {
  return [THROWAWAY, `${THROWAWAY}-journal`, `${THROWAWAY}-wal`, `${THROWAWAY}-shm`];
}

async function seed() {
  const { default: Database } = await import("better-sqlite3");
  const { hashPassword } = await import("../auth.js");
  const folder = path.join(SERVER_ROOT, "migrations/sqlite");
  const journal = JSON.parse(fs.readFileSync(path.join(folder, "meta/_journal.json"), "utf8"));
  const db = new Database(THROWAWAY);
  for (const entry of journal.entries) {
    const sql = fs.readFileSync(path.join(folder, `${entry.tag}.sql`), "utf8");
    for (const stmt of sql.split("--> statement-breakpoint")) if (stmt.trim()) db.exec(stmt);
  }

  db.prepare("insert into users (username, email, full_name, phone, password, role) values (?,?,?,?,?,?)").run(
    "smoke_customer",
    "smoke_customer@example.test",
    "Smoke Customer",
    "+216 27 903 117",
    await hashPassword("smoke_pw"),
    "client",
  );
  db.prepare(
    "insert into products (name, description, image_url, category, quantity, price) values (?,?,?,?,?,?)",
  ).run("Boîte kraft", "d", "/x.png", "Cadeaux & Décor", 12, 25);

  const uid = Number(
    (db.prepare("select id from users where username = 'smoke_customer'").get() as { id: number }).id,
  );
  const pid = Number((db.prepare("select id from products limit 1").get() as { id: number }).id);
  const insert = db.prepare(
    `insert into orders (user_id, customer_name, email, phone, address, notes, items_json,
       subtotal, total, fulfillment_method, delivery_fee, status, payment_method, created_at)
     values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
  );
  const item = (over: Record<string, unknown> = {}) =>
    JSON.stringify([
      {
        id: pid,
        name: "Boîte kraft",
        quantity: 2,
        price: 20,
        originalPrice: 25,
        promoApplied: true,
        imageUrl: "/x.png",
        ...over,
      },
    ]);

  // Delivery + promotion + pending: the timeline's first step.
  insert.run(uid, "Smoke Customer", "smoke_customer@example.test", "+216 27 903 117",
    "10 rue de Tunis", "Livrer avant 18h", item(), "40", "47", "delivery", "7", "pending", "cash_on_delivery", 1_700_000_000);
  // Pickup + ready: the last pickup-specific label is exercised here.
  insert.run(uid, "Smoke Customer", "smoke_customer@example.test", "+216 27 903 117",
    null, null, item({ originalPrice: 20, promoApplied: false }), "40", "40", "pickup", "0", "ready", "pickup", 1_700_000_100);
  // Cancelled: must not render the later steps as reached.
  insert.run(uid, "Smoke Customer", "smoke_customer@example.test", "+216 27 903 117",
    "10 rue de Tunis", null, item({ originalPrice: 20, promoApplied: false }), "40", "47", "delivery", "7", "cancelled", "cash_on_delivery", 1_700_000_200);
  // A row from before the promotion feature.
  insert.run(uid, "Smoke Customer", "smoke_customer@example.test", "+216 27 903 117",
    null, null, JSON.stringify([{ id: pid, name: "Boîte kraft", quantity: 3, price: 20 }]),
    "60", "60", "pickup", "0", "delivered", "pickup", 1_700_000_300);
  db.close();
  return { uid, pid };
}

async function main() {
  for (const f of dbFiles()) if (fs.existsSync(f)) fs.rmSync(f);
  const ids = await seed();
  // Written here rather than committed: the harness should be runnable straight
  // from a clean checkout.
  fs.writeFileSync(
    CHILD_ENV_FILE,
    [
      "# Generated by scripts/smoke-account-ui.ts. Never commit.",
      "DATABASE_URL=file:./smoke_ui.db",
      `PORT=${PORT}`,
      "HOST=127.0.0.1",
      "SESSION_SECRET=smoke-ui-secret",
      "CLOUDINARY_CLOUD_NAME=",
      "CLOUDINARY_API_KEY=",
      "CLOUDINARY_API_SECRET=",
      "",
    ].join("\n"),
  );

  const child: ChildProcess = spawn(process.execPath, [tsxCli, "index.ts"], {
    cwd: SERVER_ROOT,
    env: { ...process.env, ENV_FILE: CHILD_ENV_FILE },
    stdio: ["ignore", "pipe", "pipe"],
  });
  let log = "";
  child.stdout?.on("data", (d) => (log += d.toString()));
  child.stderr?.on("data", (d) => (log += d.toString()));

  try {
    let up = false;
    for (let i = 0; i < 120 && !up; i++) {
      await new Promise((r) => setTimeout(r, 500));
      try {
        if ((await fetch(`${BASE}/api/products?limit=1`)).ok) up = true;
      } catch {
        /* not listening yet */
      }
    }
    if (!up) throw new Error(`server never came up:\n${log}`);

    const login = await fetch(`${BASE}/api/login`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ username: "smoke_customer", password: "smoke_pw" }),
    });
    const cookie = (login.headers.get("set-cookie") || "").split(";")[0];
    if (!cookie) throw new Error(`login failed: ${login.status} ${await login.text()}`);

    console.log(`\nAPI ready on ${BASE}`);
    console.log(`customer: smoke_customer / smoke_pw   (role client, user id ${ids.uid})`);
    console.log(`session cookie: ${cookie}`);
    console.log(`\nOpen the Vite dev server on http://127.0.0.1:5173 and check:`);
    console.log(`  /account                       profile summary + 4 orders`);
    console.log(`  /account/orders/${1}             delivery + promo + pending`);
    console.log(`  /account/orders/${2}             pickup + ready (Collectée label)`);
    console.log(`  /account/orders/${3}             cancelled (no later steps)`);
    console.log(`  /account/orders/${4}             pre-promotion row (no strike-through)`);
    console.log(`  /account/orders/9999           not-found state`);
    console.log(`  log in as a customer with no order to see the empty state`);
    console.log(`\nTo assert a 404 for another customer, run the server against`);
    console.log(`test:account-routes, which covers that automatically.`);
    console.log(`\nPress Ctrl+C to stop.`);
    await waitForInterrupt();
  } finally {
    child.kill();
    await new Promise((r) => setTimeout(r, 500));
    for (const f of dbFiles()) if (fs.existsSync(f)) fs.rmSync(f);
    if (fs.existsSync(CHILD_ENV_FILE)) fs.rmSync(CHILD_ENV_FILE);
    console.log("[cleanup] server stopped, throwaway database and env file removed");
  }
}

/**
 * Resolve on Ctrl+C instead of awaiting a promise that never settles: the `finally`
 * block has to run to kill the child and remove the throwaway database.
 */
function waitForInterrupt(): Promise<void> {
  return new Promise((resolve) => {
    const stop = () => {
      process.off("SIGINT", stop);
      process.off("SIGTERM", stop);
      resolve();
    };
    process.on("SIGINT", stop);
    process.on("SIGTERM", stop);
  });
}

main().catch((e) => {
  console.error("[smoke:account-ui] failed:", e);
  process.exit(1);
});